const data = [
  {
    id: 1,
    title: "Fancy Product",
    price: 40.0,
    type: "special item",
    specialOffer: false,
    prevPrice: 40.0,
    addedToCart: false,
  },
  {
    id: 2,
    title: "Fancy Product",
    price: 18.0,
    type: "",
    specialOffer: true,
    prevPrice: 20.0,
    addedToCart: false,
  },
  {
    id: 3,
    title: "Fancy Product",
    price: 25.0,
    type: "",
    specialOffer: false,
    prevPrice: 25.0,
    addedToCart: false,
  },
  {
    id: 4,
    title: "Fancy Product",
    price: 40.0,
    type: "popular item",
    specialOffer: true,
    prevPrice: 40.0,
    addedToCart: false,
  },
  {
    id: 5,
    title: "Fancy Product",
    price: 40.0,
    type: "",
    specialOffer: false,
    prevPrice: 40.0,
    addedToCart: false,
  },
  {
    id: 6,
    title: "Fancy Product",
    price: 120.0,
    type: "",
    specialOffer: false,
    prevPrice: 120.0,
    addedToCart: false,
  },
  {
    id: 7,
    title: "Fancy Product",
    price: 18.0,
    type: "special item",
    specialOffer: true,
    prevPrice: 20.0,
    addedToCart: false,
  },
  {
    id: 8,
    title: "Fancy Product",
    price: 40.0,
    type: "popular item",
    specialOffer: true,
    prevPrice: 40.0,
    addedToCart: false,
  },
];

export default data;
